import type { ClusterLike, SecretMetaLike } from "./types";

const CERT_MANAGER = "cert-manager.io/";

export interface IssuedBy {
  certificate: string;
  issuer: string;
  issuerKind: string;
}

export interface TlsSecretView {
  role: "Server" | "Server CA" | "Client CA" | "Replication";
  secret: string;
  /** cert-manager when its annotations are on the Secret; else the operator's own, or one given. */
  source: { certManager: IssuedBy } | "operator" | "provided";
}

const ROLES = [
  ["Server", "serverTLSSecret"],
  ["Server CA", "serverCASecret"],
  ["Client CA", "clientCASecret"],
  ["Replication", "replicationTLSSecret"],
] as const;

/** Each Secret Postgres's TLS uses, and who issued it. Before Secrets are listed, nothing is claimed. */
export function tlsSecretsOf(
  cluster: ClusterLike,
  secrets: SecretMetaLike[] | undefined,
): TlsSecretView[] {
  const used = { ...cluster.status?.certificates, ...cluster.spec.certificates };
  const given = cluster.spec.certificates ?? {};

  return ROLES.flatMap(([role, key]) => {
    const secret = used[key];

    if (!secret) return [];

    const annotations = (secrets ?? []).find(
      (each) => each.metadata.name === secret && each.metadata.namespace === cluster.getNs(),
    )?.metadata.annotations;
    const certificate = annotations?.[`${CERT_MANAGER}certificate-name`];

    return [
      {
        role,
        secret,
        source: certificate
          ? {
              certManager: {
                certificate,
                issuer: annotations?.[`${CERT_MANAGER}issuer-name`] ?? "",
                issuerKind: annotations?.[`${CERT_MANAGER}issuer-kind`] || "Issuer",
              },
            }
          : given[key]
            ? "provided"
            : "operator",
      },
    ];
  });
}

export function describeSource(view: TlsSecretView): string {
  if (view.source === "operator") return "generated by CloudNativePG";
  if (view.source === "provided") return "provided, not by cert-manager";

  const { certificate, issuerKind, issuer } = view.source.certManager;

  return `issued by cert-manager (Certificate ${certificate}, ${issuerKind} ${issuer})`;
}

/** Whether the server certificate came from cert-manager, for the list. */
export function serverTlsSource(views: TlsSecretView[]): "cert-manager" | "operator" | "provided" {
  const server = views.find((each) => each.role === "Server");

  if (!server || server.source === "operator") return "operator";

  return server.source === "provided" ? "provided" : "cert-manager";
}

export interface ConnectionView {
  label: string;
  url: string;
}

/** Without the password: it is in the app Secret, which Freelens never reads. */
export function connectionUrls(cluster: ClusterLike): ConnectionView[] {
  const name = cluster.getName();
  const namespace = cluster.getNs() ?? "default";
  const database = cluster.spec.bootstrap?.initdb?.database ?? "app";
  const owner = cluster.spec.bootstrap?.initdb?.owner ?? database;
  // CloudNativePG always serves TLS; require it, or a client may fall back to plain text.
  const url = (service: string) =>
    `postgresql://${owner}@${name}-${service}.${namespace}.svc:5432/${database}?sslmode=require`;

  return [
    { label: "Primary (read-write)", url: url("rw") },
    { label: "Replicas (read-only)", url: url("ro") },
  ];
}

export function fullUrlCommand(cluster: ClusterLike): string {
  return `kubectl get secret -n ${cluster.getNs() ?? "default"} ${cluster.getName()}-app -o jsonpath='{.data.uri}' | base64 -d`;
}

export const METADATA_ONLY = "application/json;as=PartialObjectMetadataList;g=meta.k8s.io;v=v1";

export interface PartialObjectMetadataList {
  items?: {
    metadata?: { name?: string; namespace?: string; annotations?: Record<string, string> };
  }[];
}

/** Names and cert-manager's annotations: the rest is dropped on arrival, since last-applied carries the values. */
export function secretNamesFrom(list: PartialObjectMetadataList): SecretMetaLike[] {
  return (list.items ?? []).flatMap((item) => {
    const metadata = item.metadata;

    if (!metadata?.name) return [];

    const annotations = Object.fromEntries(
      Object.entries(metadata.annotations ?? {}).filter(([key]) => key.startsWith(CERT_MANAGER)),
    );

    return [{ metadata: { name: metadata.name, namespace: metadata.namespace, annotations } }];
  });
}
