import { describe, expect, it } from "vitest";

import {
  connectionUrls,
  describeSource,
  fullUrlCommand,
  secretNamesFrom,
  serverTlsSource,
  tlsSecretsOf,
} from "../src/renderer/api/connection";
import type { ClusterLike } from "../src/renderer/api/types";
import { clusters, secrets } from "./fixtures";

const cluster = (name: string) => {
  const found = clusters().find((each) => each.getName() === name);

  if (!found) throw new Error(`no ${name} in the fixture`);

  return found;
};

describe("which Secrets a cluster's TLS uses", () => {
  it("says cert-manager issued the server certificate it was given", () => {
    const views = tlsSecretsOf(cluster("inventory-db"), secrets());
    const server = views.find((each) => each.role === "Server");

    expect(server).toEqual({
      role: "Server",
      secret: "inventory-db-server-tls",
      source: {
        certManager: {
          certificate: "inventory-db-server-tls",
          issuer: "demo-ca",
          issuerKind: "ClusterIssuer",
        },
      },
    });
    expect(server && describeSource(server)).toBe(
      "issued by cert-manager (Certificate inventory-db-server-tls, ClusterIssuer demo-ca)",
    );
    expect(serverTlsSource(views)).toBe("cert-manager");
  });

  it("says the operator generated the ones nobody gave it", () => {
    const views = tlsSecretsOf(cluster("orders-db"), secrets());

    expect(views.map((each) => [each.role, each.secret])).toEqual([
      ["Server", "orders-db-server"],
      ["Server CA", "orders-db-ca"],
      ["Client CA", "orders-db-ca"],
      ["Replication", "orders-db-replication"],
    ]);
    expect(views.every((each) => each.source === "operator")).toBe(true);
    expect(views[0] && describeSource(views[0])).toBe("generated by CloudNativePG");
    expect(serverTlsSource(views)).toBe("operator");
  });

  it("calls a given Secret provided when cert-manager's annotations are not on it, or not listed yet", () => {
    const views = tlsSecretsOf(cluster("inventory-db"), undefined);
    const server = views.find((each) => each.role === "Server");

    expect(server?.source).toBe("provided");
    expect(server && describeSource(server)).toBe("provided, not by cert-manager");
    expect(serverTlsSource(views)).toBe("provided");
    expect(serverTlsSource([])).toBe("operator");
  });

  it("falls back to Issuer when the kind annotation is empty", () => {
    const listed = secrets().map((each) =>
      each.metadata.name === "inventory-db-server-tls"
        ? {
            metadata: {
              ...each.metadata,
              annotations: { "cert-manager.io/certificate-name": "x" },
            },
          }
        : each,
    );
    const server = tlsSecretsOf(cluster("inventory-db"), listed).find(
      (each) => each.role === "Server",
    );

    expect(server?.source).toEqual({
      certManager: { certificate: "x", issuer: "", issuerKind: "Issuer" },
    });
  });
});

describe("connecting", () => {
  it("offers the read-write and read-only URLs, without the password, requiring TLS", () => {
    expect(connectionUrls(cluster("orders-db"))).toEqual([
      {
        label: "Primary (read-write)",
        url: "postgresql://app@orders-db-rw.databases.svc:5432/app?sslmode=require",
      },
      {
        label: "Replicas (read-only)",
        url: "postgresql://app@orders-db-ro.databases.svc:5432/app?sslmode=require",
      },
    ]);
  });

  it("uses the database and owner initdb names, and defaults the owner to the database", () => {
    const base = cluster("orders-db");
    const named = (initdb: { database?: string; owner?: string }) =>
      ({
        ...base,
        getName: () => base.getName(),
        getNs: () => base.getNs(),
        spec: { ...base.spec, bootstrap: { initdb } },
      }) as unknown as ClusterLike;

    expect(connectionUrls(named({ database: "shop", owner: "web" }))[0]?.url).toBe(
      "postgresql://web@orders-db-rw.databases.svc:5432/shop?sslmode=require",
    );
    expect(connectionUrls(named({ database: "shop" }))[0]?.url).toBe(
      "postgresql://shop@orders-db-rw.databases.svc:5432/shop?sslmode=require",
    );
  });

  it("reads the full URL from the app Secret in the terminal, not in Freelens", () => {
    expect(fullUrlCommand(cluster("orders-db"))).toBe(
      "kubectl get secret -n databases orders-db-app -o jsonpath='{.data.uri}' | base64 -d",
    );
  });
});

describe("listing Secrets", () => {
  it("keeps cert-manager's annotations and drops everything else", () => {
    expect(
      secretNamesFrom({
        items: [
          {
            metadata: {
              name: "s",
              namespace: "n",
              annotations: {
                "cert-manager.io/issuer-name": "ca",
                "kubectl.kubernetes.io/last-applied-configuration": "{}",
              },
            },
          },
          { metadata: {} },
        ],
      }),
    ).toEqual([
      {
        metadata: {
          name: "s",
          namespace: "n",
          annotations: { "cert-manager.io/issuer-name": "ca" },
        },
      },
    ]);
    expect(secretNamesFrom({})).toEqual([]);
  });
});
